# Глобальные настройки Prometheus (ClickHouse stack)
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'clickhouse-dev-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'clickhouse'
    metrics_path: /metrics
    static_configs:
      - targets: ['clickhouse:9363']
        labels:
          instance: 'clickhouse-dev'


